arction/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('authentication.urls')),
    path('lelang/', include('lelang.urls')),
    path('profil/', include('profil.urls')),
]

authentication/urls.py
from django.urls import path
from .views import *

app_name = "authentication"

urlpatterns = [
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('logout/', logout, name="logout"),
    path('register-penjual/', daftar_sebagai_penjual, name="register-penjual"),
    path('register-penjual/respond', daftar_sebagai_penjual_respond, name="register-penjual-respond"),
    path('register-penjual/validation', admin_validation_page, name="admin-validation"),
    path('register-penjual/validation/accept/<int:id>', admin_validation_accept, name="admin-validation-accept"),
    path('register-penjual/validation/decline/<int:id>', admin_validation_decline, name="admin-validation-decline"),
]

homepage/urls.py
from django.urls import path
from .views import homepage

app_name = "homepage"

urlpatterns = [
    path('', homepage, name="homepage")
]

lelang/urls.py
from django.urls import path
from .views import *

app_name = "lelang"

urlpatterns = [
    path('create/', create, name="create"),
    path('update/<int:id>', update, name="update"),
    path('createtest/', createtest, name="createtest"),
    path('updatetest/', updatetest, name="updatetest"),
    path('<int:id>', each_lelang, name="each_lelang"),
    path('', list_lelang, name="list_lelang"),
    path('raisebid/<int:id>', raise_bid, name="raisebid"),
    path('buyout/<int:id>', buyout, name="buyout")
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.shortcuts import render, redirect
from django.core.serializers import serialize
from profil.models import *
import re

# Create your views here.
def login(request):
    if request.method == "POST":
        username = request.POST['username'].strip().lower()
        password = request.POST['password']
        if len(username) == 0 or len(password) == 0 or " " in username:
            ## If form not valid
            dct = {
                'message' : 'form_not_valid'
            }
            return render(request, 'authentication/login.html', dct)
        else:
            try:
                user = Akun.objects.get(username=username)
                password_is_correct = password_checker(password, user.password)
                if (password_is_correct):
                    request.session['username'] = username
                    role = []
                    is_pengguna = check_is_pengguna(username)
                    is_penjual = check_is_penjual(username)
                    is_admin = check_is_admin(username)
                    if is_pengguna:
                        role.append('pengguna')
                    if is_penjual:
                        user = Penjual.objects.get(username=username)
                        role.append('penjual')
                    
                    if is_admin:
                        role.append('admin')
                    request.session['role'] = role
                    return redirect('/')
                else:
                    ## If wrong password
                    dct = {
                        'message' : 'failed_auth'
                    }
                    return render(request, 'authentication/login.html', dct)
            except:
                ## If user account does not exist
                dct = {
                    'message' : 'not_exist'
                }
                return render(request, 'authentication/login.html', dct)
    else:
        return render(request, 'authentication/login.html')

def check_is_admin(username):
    count = Admin.objects.filter(username=username)
    return len(count) == 1

def check_is_pengguna(username):
    count = Pengguna.objects.filter(username=username)
    return len(count) == 1

def check_is_penjual(username):
    count = Penjual.objects.filter(username=username)
    return len(count) == 1

def password_checker(input_password, real_password):
    return input_password == real_password

def register(request):
    if request.method == "POST":
        nama = request.POST['nama']
        email = request.POST['email'].strip().lower()
        username = request.POST['username'].strip().lower()
        password = request.POST['password']
        if len(nama) == 0 or len(email) == 0 or len(username) < 6 or len(password) < 6 or " " in username or not validate_email(email):
            dct = {
                    'message' : 'form_not_valid'
                }
            return render(request, 'authentication/register.html', dct)
            
        else:
            username_is_exist = username_exist_checker(username)
            if (username_is_exist == False):
                user = Pengguna.objects.create(username=username, password=password, nama=nama, email=email, saldo=0)
                request.session['username'] = username
                request.session['role'] = ['pengguna']
                return redirect('/')
            else:
                ## If user account already exist
                dct = {
                    'message' : 'exist'
                }
                return render(request, 'authentication/register.html', dct)
    else:
        return render(request, 'authentication/register.html')

def username_exist_checker(username):
    count = Akun.objects.filter(username=username)
    return len(count) == 1

def validate_email(email):
    if re.match('^[a-z0-9]+[\._]?[a-z0-9]+[@]\w+([.]\w+)+$', email):
        return True
    else:
        return False

def daftar_sebagai_penjual(request):
    try:
        username = request.session['username']
        if len(username) == 0:
            return redirect("/")
        if 'penjual' in request.session['role'] or check_is_penjual(username):
            return redirect("/")
    except:
        return redirect("/")
       
    if request.method == "POST":
        username = request.session['username']
        nomor_identitas = request.POST['nomor_identitas']
        if len(nomor_identitas) < 10:
            response = {
                'message' : 'form_not_valid'
            }
            return render(request, 'authentication/seller.html', response)
        else:
            response = {}
            if check_request_penjual_exist(username):
                return redirect("/")
            req = RequestPenjual.objects.create(
                username=username, 
                status='menunggu persetujuan',
                nomor_identitas=nomor_identitas
            )
            response["status_request"] = 'menunggu persetujuan'
            return render(request, 'authentication/sellerrespond.html', response)
    else:
        username = request.session['username']
        if check_request_penjual_exist(username):
            res = daftar_sebagai_penjual_respond(request)
            return res
        return render(request, 'authentication/seller.html')

def daftar_sebagai_penjual_respond(request):
    # check not penjual role
    try:
        username = request.session['username']
        if len(username) == 0:
            return redirect("/")
        if 'penjual' in request.session['role'] or check_is_penjual(username):
            return redirect("/")
    except:
        return redirect("/")
    
    username = request.session['username']
    if not check_request_penjual_exist(username):
        return render(request, 'authentication/seller.html')

    response = {}
    req = RequestPenjual.objects.get(username=username)
    response["status_request"] = req.status
    if req.status == "ditolak":
        req.delete()
    return render(request, 'authentication/sellerrespond.html', response)

def check_request_penjual_exist(username):
    count = RequestPenjual.objects.filter(username=username)
    return len(count) == 1

def admin_validation_page(request):
    response = {}
    # check admin role
    try:
        username = request.session['username']
        if len(username) == 0:
            return redirect("/")
        if 'admin' not in request.session['role'] or not check_is_admin(username):
            return redirect("/")
    except:
        return redirect("/")

    req_list = RequestPenjual.objects.filter(status='menunggu persetujuan')
    response['req_list'] = req_list 
    return render(request, 'authentication/adminvalidation.html', response)

def admin_validation_accept(request, id):
    response = {}
    try:
        req = RequestPenjual.objects.get(id=id)
        print(req.username)
        pengguna = Pengguna.objects.get(username=req.username)
        print(pengguna)
        penjual = Penjual(
            username=pengguna.username, 
            password=pengguna.password, 
            nama=pengguna.nama, 
            email=pengguna.email, 
            saldo=0,
            pengguna_ptr=pengguna, 
            nomor_identitas=req.nomor_identitas,
        )
        print(penjual)
        penjual.save()
        flag = True

        req.status = "diterima"
        req.save()
        response['message'] = "success"
    except:
        response['message'] = "failed"
    
    req_list = RequestPenjual.objects.filter(status='menunggu persetujuan')
    response['req_list'] = req_list 
    return render(request, 'authentication/adminvalidation.html', response)

def admin_validation_decline(request, id):
    response = {}
    try:
        req = RequestPenjual.objects.get(id=id)
        req.status = "ditolak"
        req.save()
        response['message'] = "success"
    except:
        response['message'] = "failed"
    req_list = RequestPenjual.objects.filter(status='menunggu persetujuan')
    response['req_list'] = req_list 
    return render(request, 'authentication/adminvalidation.html', response)


def logout(request):
    request.session.flush()
    return redirect('/')

authentication/templates/authentication/adminvalidation.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/authentication/authentication.css' %}">
{% endblock %}

{% block content %}
<div class="history">
    <div class="header">
        <p class="mb-0">Permintaan Menjadi Penjual</p>
        {% if message == "success" %}
            <p class="mb-0 form-success">Permintaan berhasil dilakukan</p>
        {% elif message == "failed" %}
            <p class="mb-0 form-warning">Terjadi Kesalahan</p>
        {% endif %}
    </div>
    {% for req in req_list %}
        <div class="kartu d-flex flex-row flex-wrap">
            <div class="kartu-info">
                <p>Username: {{ req.username }}</p>
                <p>Nomor Identitas: {{ req.nomor_identitas }}  </p>
            </div>
            <div class="kartu-header ml-auto">
                <div class="">
                    <a href="{% url 'authentication:admin-validation-accept' id=req.id %}">
                        <button class="validation-button green-button">Terima</button>
                    </a>
                    <a href="{% url 'authentication:admin-validation-decline' id=req.id %}">
                        <button class="validation-button red-button">Tolak</button>
                    </a>
                </div>
            </div>
            
        </div>
    {% endfor %}
</div>

{% include 'footer.html' %}

{% endblock %}

authentication/templates/authentication/login.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/authentication/authentication.css' %}">
{% endblock %}

{% block content %}
<div class="auth">
    <img class="gallery" src="{% static 'images/gallery.jpg' %}" alt="Gallery">
    <form class="auth-form" method="POST" action="">
        {% csrf_token %}
        <div class="form-header">
            <p class="mb-0">Masuk</p>
            {% if message == "not_exist" %}
            <p class="form-warning">
                User does not exist!
            </p>
            {% elif message == "failed_auth" %}
            <p class="form-warning">
                Wrong username or password!
            </p>
            {% endif %}
        </div>
        <div class="form-row">
            <div class="form-tag">
                <p class="mb-0">Username</p>
            </div>
            <div class="form-input">
                <input type="text" class="form" name="username" required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-tag">
                <p class="mb-0">Password</p>
            </div>
            <div class="form-input">
                <input type="password" class="form" name="password" required>
            </div>
        </div>
        <p style="text-align: center;" class="mb-0"><button class="auth-button" type="submit">Masuk</button></p>
    </form>
</div>
{% endblock %}

authentication/templates/authentication/register.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/authentication/authentication.css' %}">
{% endblock %}

{% block content %}
<div class="auth">
    <img class="gallery" src="{% static 'images/gallery.jpg' %}" alt="Gallery">
    <form class="auth-form" method="POST" action="">
        {% csrf_token %}
        <div class="form-header">
            <p class="mb-0">Daftar</p>
            {% if message == "exist" %}
                <p class="form-warning">
                    Account already exist!
                </p>
            {% elif message == "form_not_valid" %}
                <p class="form-warning">
                    Form not valid!
                </p>
            {% endif %}
        </div>
        <div class="form-row">
            <div class="form-tag">
                <p class="mb-0">Nama</p>
            </div>
            <div class="form-input">
                <input type="text" class="form" name="nama" required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-tag">
                <p class="mb-0">Email</p>
            </div>
            <div class="form-input">
                <input type="email" class="form" name="email" required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-tag">
                <p class="mb-0">Username</p>
            </div>
            <div class="form-input">
                <input type="text" class="form" name="username" required>
            </div>
        </div>
        <div class="form-row">
            <div class="form-tag">
                <p class="mb-0">Password</p>
            </div>
            <div class="form-input">
                <input type="password" class="form" name="password" required>
            </div>
        </div>
        <p style="text-align: center;" class="mb-0"><button class="auth-button" type="submit">Daftar</button></p>
    </form>
</div>
{% endblock %}

authentication/templates/authentication/seller.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/authentication/authentication.css' %}">
{% endblock %}

{% block content %}
<div class="auth">
    <img class="gallery" src="{% static 'images/seller.jpg' %}" alt="Gallery">
    <form class="auth-form" method="POST" action="">
        {% csrf_token %}
        <div class="form-header">
            <p class="mb-0">Daftar Sebagai Penjual</p>
            {% if message == "form_not_valid" %}
                <p class="form-warning">
                    Nomor Identitas kurang dari 10 karakter
                </p>
            {% endif %}
        </div>
        <div class="form-row">
            <div class="form-tag">
                <p class="mb-0">Nomor Identitas</p>
            </div>
            <div class="form-input">
                <input type="text" class="form" name="nomor_identitas" required>
            </div>
        </div>
        <p style="text-align: center;" class="mb-0"><button class="auth-button" type="submit">Daftar</button></p>
    </form>
</div>
{% endblock %}

authentication/templates/authentication/sellerrespond.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/authentication/authentication.css' %}">
{% endblock %}

{% block content %}
<div class="auth">
    <img class="gallery" src="{% static 'images/seller.jpg' %}" alt="Gallery">
    {% if status_request == "menunggu persetujuan"%}
    <div class="auth-form">
        <div class="form-header">
            <p class="mb-0">Menunggu Persetujuan Admin</p>
        </div>
        <p class="text-center" class="mb-0">
            <a href="{% url 'homepage:homepage' %}">
                <button class="auth-button" type="submit">Kembali ke Halaman Utama</button>
            </a>
        </p>
    </div>
    {% elif status_request == "diterima" %}
    <div class="auth-form">
        <p class="text-center">
            <img class="max-width-10" src="{% static 'images/seller_respond/approve.png' %}" alt="approve">
        </p>
        <div class="form-header">
            <p class="text-center mb-0">Permintaan diterima</p>
        </div>
        <p class="text-center mb-0">
            <a href="{% url 'homepage:homepage' %}">
                <button class="auth-button" type="submit">Kembali ke Halaman Utama</button>
            </a>
        </p>
    </div>
    {% elif status_request == "ditolak" %}
    <div class="auth-form">
        <p class="text-center">
            <img class="max-width-10" src="{% static 'images/seller_respond/decline.png' %}" alt="decline">
        </p>
        <div class="form-header">
            <p class="mb-0 red text-center">Permintaan ditolak</p>
        </div>
        <p class="text-center mb-0">
        <a href="{% url 'authentication:register-penjual' %}">
            <button class="auth-button max-width-10 padding-respond-button" type="submit">Ulangi Pendaftaran</button>
        </a>
        <a href="{% url 'homepage:homepage' %}">
            <button class="red-button auth-button max-width-10 padding-respond-button" type="submit">Kembali ke Halaman Utama</button>
        </a>
        </p>
    </div>
    {% endif %}
</div>
{% endblock %}