arction/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('authentication.urls')),
    path('lelang/', include('lelang.urls')),
    path('profil/', include('profil.urls')),
]

lelang/urls.py
from django.urls import path
from .views import *

app_name = "lelang"

urlpatterns = [
    path('create/', create, name="create"),
    path('update/<int:id>', update, name="update"),
    path('createtest/', createtest, name="createtest"),
    path('updatetest/', updatetest, name="updatetest"),
    path('<int:id>', each_lelang, name="each_lelang"),
    path('', list_lelang, name="list_lelang"),
    path('raisebid/<int:id>', raise_bid, name="raisebid"),
    path('buyout/<int:id>', buyout, name="buyout")
]

profil/urls.py
from django.urls import path
from .views import *

app_name = "profil"

urlpatterns = [
    path('history-terbeli/', history_terbeli, name="history_terbeli"),
    path('history-terjual/', history_terjual, name="history_terjual"),
    path('lelang-dibuat/', lelang_dibuat, name="lelang_dibuat"),
    path('lelang-diikuti/', lelang_diikuti, name="lelang_diikuti"),
]

profil/models.py
from django.db import models

# Create your models here.
class Akun(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return self.username

class Admin(Akun):

    def __str__(self):
        return super().__str__()

class Pengguna(Akun):
    email = models.EmailField(max_length=50)
    nama = models.CharField(max_length=100)
    saldo = models.IntegerField()

    def __str__(self):
        return self.nama
    
    def set_saldo(self, new_saldo):
        self.saldo = new_saldo
    
    def get_saldo(self):
        return self.saldo

class Penjual(Pengguna):
    nomor_identitas = models.CharField(max_length=50)

    def __str__(self):
        return super().__str__()

class Request(models.Model):
    username = models.CharField(max_length=50)
    status = models.CharField(max_length=50)
    
    def __str__(self):
        return self.username

class RequestPenjual(Request):
    nomor_identitas = models.CharField(max_length=50)

    def __str__(self):
        return super().__str__()

profil/views.py
from django.shortcuts import render
from lelang.models import *
from datetime import datetime, timedelta
import pytz
from django.http import HttpResponseNotFound

# Create your views here.
def history_terbeli(request):
    authenticated = request.session.__contains__('username')
    if (authenticated):
        pengguna = Pengguna.objects.get(username=request.session['username'])
        transaksi = Transaksi.objects.filter(pengguna=pengguna)
        dct = {
            "transaksi" : transaksi
        }
        return render(request, 'profil/daftar_barang_terbeli.html',  dct)
    else:
        return HttpResponseNotFound("404 Not Found")

def history_terjual(request):
    authenticated = request.session.__contains__('username')
    if (authenticated):
        if (Penjual.objects.filter(username=request.session['username'])):
            penjual = Penjual.objects.get(username=request.session['username'])
            lelang_penjual = Lelang.objects.filter(lelang_penjual=penjual)
            lelang_berhasil = []
            for objek in lelang_penjual:
                if(objek.lelang_highestbidder is not None and 
                objek.get_lelang_endtime() < datetime.now(pytz.timezone('Asia/Bangkok'))):
                    lelang_berhasil.append(objek)
            dct = {
                'lelang_berhasil' : lelang_berhasil,
            }
            return render(request, 'profil/daftar_barang_terjual.html', dct)
        else:
            return HttpResponseNotFound("404 NOT FOUND")
    else:
        return HttpResponseNotFound("404 NOT FOUND")


def lelang_dibuat(request):
    authenticated = request.session.__contains__('username')
    if (authenticated):
        if (Penjual.objects.filter(username=request.session['username'])):
            penjual = Penjual.objects.get(username=request.session['username'])
            lelang = Lelang.objects.filter(lelang_penjual=penjual)
            lelang_with_status = []
            for objek in lelang:
                if (objek.lelang_starttime - datetime.now(pytz.timezone('Asia/Bangkok')) > timedelta(0)):
                    lelang_with_status.append([objek, True])
                else:
                    lelang_with_status.append([objek, False])
            dct = {
                'lst' : lelang_with_status,
                'time' : datetime.now(),
            }
            return render(request, 'profil/daftar_lelang_dibuat.html', dct)
        else:
            return HttpResponseNotFound("404 NOT FOUND")
    else:
        return HttpResponseNotFound("404 NOT FOUND")

def lelang_diikuti(request):
    return render(request, 'profil/daftar_lelang_diikuti.html')

profil/templates/profil/daftar_barang_terbeli.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/profil/card_barang.css' %}">
{% endblock %}

{% block content %}
<div class="history">
    <div class="header">
        <p class="mb-0">Daftar Barang Terbeli</p>
    </div>
    <div style="min-height: 80vh;">
        {% if transaksi.count > 0 %}
            {% for trans in transaksi %}
                <div class="kartu">
                    <p>{{ trans.get_tanggal_terbuat }}</p>
                    <div class="kartu-info">
                        <div class="barang-image">
                            <img src="{{ trans.get_url_image }}" alt="Barang">
                        </div>
                        <div class="barang-detail">
                            <p>{{ trans.get_nama_barang }}</p>
                            <p>Rp {{ trans.get_currentbid_price }},-</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p style="text-align: center;" class="mb-0">Belum ada barang yang terbeli!</p>
        {% endif %}
    </div>
</div>

{% include 'footer.html' %}

{% endblock %}

profil/templates/profil/daftar_barang_terjual.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/profil/card_barang.css' %}">
{% endblock %}

{% block content %}

{% if "penjual" in request.session.role %}

    <div class="history">
        <div class="header">
            <p class="mb-0">Daftar Barang Terjual</p>
        </div>
        
        <div style="min-height: 80vh;">
            {% if lelang_berhasil %}
                {% for lelang_berhasil in lelang_berhasil %}
                <div class="kartu">
                    <p>{{ lelang_berhasil.lelang_endttime }}</p>
                    <div class="kartu-info">
                        <div class="barang-image">
                            <img src="{{ lelang_berhasil.get_url_image }}" alt="Barang">
                        </div>
                        <div class="barang-detail">
                            <p>{{ lelang_berhasil.lelang_barang.barang_nama }}</p>
                            <p>Pembeli : {{ lelang_berhasil.lelang_highestbidder }}</p>
                            {% if lelang_berhasil.lelang_currentbid > lelang_berhasil.lelang_buyout %}
                                <p>Rp {{ lelang_berhasil.lelang_currentbid }},-</p>
                            {% else %}
                                <p>Rp {{ lelang_berhasil.lelang_buyout }},-</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            {% else %}
                <p style="text-align: center;" class="mb-0">Belum ada barang yang terjual!</p>
            {% endif %}
        </div>
    </div>
{% else %}
    <div> 
        <center>
            <p>Silahkan register sebagai penjual untuk melihat history penjualan!</p>
        </center>
    </div>
{% endif %}

{% include 'footer.html' %}

{% endblock %}

profil/templates/profil/daftar_lelang_dibuat.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/profil/card_lelang.css' %}">
{% endblock %}

{% block content %}

{% if "penjual" in request.session.role %}
    <div class="history">
        <div class="header">
            <p class="mb-0">Daftar Lelang yang Dibuat</p>
        </div>
        <div style="min-height: 80vh;">
            {% if lst %}
                {% for lelang, is_editable in lst %}
                    <div class="kartu">
                        <div class="kartu-header">
                            <p>{{ lelang.lelang_starttime }} - {{ lelang.lelang_endtime }}</p>
                            {% if is_editable %}
                            <a style="margin-left:auto" href="{% url 'lelang:update' id=lelang.pk %}">
                                <button class="edit-lelang-button">Edit lelang</button>
                            </a>
                            {% endif %}
                        </div>
                        <div class="kartu-info">
                            <div class="barang-image">
                                <img src="{{ lelang.get_url_image }}" alt="Barang">
                            </div>
                            <div class="barang-detail">
                                <p>{{ lelang.lelang_barang.barang_nama }}</p>
                                <p>{{ lelang.lelang_barang.barang_deskripsi }}</p>
                                <p>Start Bid Rp {{ lelang.lelang_startingbid }},-</p>
                                <p>Minimum Raise Bid Rp {{ lelang.lelang_minraise }},-</p>
                                <p>Current Bid Rp {{ lelang.lelang_currentbid }},-</p>
                                <p>Buyout Price Rp {{ lelang.lelang_buyout }},-</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p style="text-align: center;" class="mb-0">Anda belum pernah membuat lelang!</p>
            {% endif %}
        </div>
    </div>
{% else %}
    <div> 
        <center>
            <p>Silahkan register sebagai penjual untuk membuat lelang!</p>
        </center>
    </div>
{% endif %}

{% include 'footer.html' %}

{% endblock %}

profil/templates/profil/daftar_lelang_diikuti.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/profil/card_barang.css' %}">
{% endblock %}

{% block content %}
<div class="history">
    <div class="header">
        <p class="mb-0">Daftar Lelang yang Sedang Diikuti</p>
    </div>
    <div class="kartu">
        <p>13 Des 2020</p>
        <div class="kartu-info">
            <div class="barang-image">
                <img src="{% static 'images/yellow_apple.jpeg' %}" alt="Barang">
            </div>
            <div class="barang-detail">
                <p>Apel kuning yang merona banged deh pokoknya jadi kamu harus beli</p>
                <p>Rp 1.000,-</p>
            </div>
        </div>
    </div>
    <div class="kartu">
        <p>13 Des 2020</p>
        <div class="kartu-info">
            <div class="barang-image">
                <img src="{% static 'images/yellow_apple.jpeg' %}" alt="Barang">
            </div>
            <div class="barang-detail">
                <p>Apel kuning yang merona banged deh pokoknya jadi kamu harus beli</p>
                <p>Rp 1.000,-</p>
            </div>
        </div>
    </div>
    <div class="kartu">
        <p>13 Des 2020</p>
        <div class="kartu-info">
            <div class="barang-image">
                <img src="{% static 'images/yellow_apple.jpeg' %}" alt="Barang">
            </div>
            <div class="barang-detail">
                <p>Apel kuning yang merona banged deh pokoknya jadi kamu harus beli</p>
                <p>Rp 1.000,-</p>
            </div>
        </div>
    </div>
</div>

{% include 'footer.html' %}

{% endblock %}