arction/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('authentication.urls')),
    path('lelang/', include('lelang.urls')),
    path('profil/', include('profil.urls')),
]

authentication/urls.py
from django.urls import path
from .views import *

app_name = "authentication"

urlpatterns = [
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('logout/', logout, name="logout"),
    path('register-penjual/', daftar_sebagai_penjual, name="register-penjual"),
    path('register-penjual/respond', daftar_sebagai_penjual_respond, name="register-penjual-respond"),
    path('register-penjual/validation', admin_validation_page, name="admin-validation"),
    path('register-penjual/validation/accept/<int:id>', admin_validation_accept, name="admin-validation-accept"),
    path('register-penjual/validation/decline/<int:id>', admin_validation_decline, name="admin-validation-decline"),
]

lelang/urls.py
from django.urls import path
from .views import *

app_name = "lelang"

urlpatterns = [
    path('create/', create, name="create"),
    path('update/<int:id>', update, name="update"),
    path('createtest/', createtest, name="createtest"),
    path('updatetest/', updatetest, name="updatetest"),
    path('<int:id>', each_lelang, name="each_lelang"),
    path('', list_lelang, name="list_lelang"),
    path('raisebid/<int:id>', raise_bid, name="raisebid"),
    path('buyout/<int:id>', buyout, name="buyout")
]

lelang/models.py
from django.db import models
from profil.models import *
from datetime import datetime

# Create your models here.

class Barang(models.Model):
    barang_nama = models.CharField(max_length=30)
    barang_deskripsi = models.TextField()
    barang_url = models.URLField()

    def __str__(self):
        return self.barang_nama
    
    def get_nama_barang(self):
        return self.barang_nama

    def get_deskripsi_barang(self):
        return self.barang_deskripsi
    
    def get_url_barang(self):
        return self.barang_url

class Lelang(models.Model):
    lelang_penjual = models.ForeignKey(Penjual, on_delete=models.DO_NOTHING)
    lelang_barang = models.ForeignKey(Barang, on_delete=models.DO_NOTHING)
    lelang_startingbid = models.IntegerField()
    lelang_buyout = models.IntegerField()
    lelang_minraise = models.IntegerField()
    lelang_currentbid = models.IntegerField(default=0)
    lelang_starttime = models.DateTimeField()
    lelang_endtime = models.DateTimeField()
    lelang_highestbidder = models.ForeignKey(Pengguna,null=True, on_delete=models.DO_NOTHING, related_name='highestbidder')
    lelang_listpengguna = models.ManyToManyField(Pengguna,related_name='follower')

    # Status List = ['Soon', 'Open', 'Closed']
    lelang_status = models.CharField(max_length=10, default='Soon')

    def __str__(self):
        return self.lelang_barang.__str__()

    def get_penjual(self):
        return self.lelang_penjual
    
    def get_username_penjual(self):
        return self.lelang_penjual.username
    
    def get_nama_barang(self):
        barang = self.lelang_barang
        return barang.get_nama_barang()
    
    def get_deskripsi_barang(self):
        barang = self.lelang_barang
        return barang.get_deskripsi_barang()

    def get_url_barang(self):
        barang = self.lelang_barang
        return barang.get_url_barang()
    
    def get_startingbid_price(self):
        return self.lelang_startingbid

    def get_buyout_price(self):
        return self.lelang_buyout
    
    def get_minraise_price(self):
        return self.lelang_minraise

    def get_currentbid_price(self):
        return self.lelang_currentbid
    
    def get_lelang_starttime(self):
        return self.lelang_starttime

    def get_lelang_endtime(self):
        return self.lelang_endtime
    
    def get_highestbidder(self):
        return self.lelang_highestbidder
    
    def get_listpengguna(self):
        return self.lelang_listpengguna
    
    def get_status(self):
        return self.lelang_status

class Transaksi(models.Model):
    lelang = models.ForeignKey(Lelang, on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=10, default="Paid")
    pengguna = models.ForeignKey(Pengguna, on_delete=models.DO_NOTHING)
    tanggal_terbuat = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.lelang.get_nama_barang()

    def get_lelang(self):
        return self.lelang
    
    def get_status(self):
        return self.status

    def get_pengguna(self):
        return self.pengguna

    def get_currentbid_price(self):
        return self.lelang.get_currentbid_price()

    def get_nama_barang(self):
        return self.lelang.get_nama_barang()

    def get_url_image(self):
        return self.lelang.get_url_barang()

    def get_tanggal_terbuat(self):
        return self.tanggal_terbuat

lelang/views.py
from django.shortcuts import render,redirect
from profil.models import *
from .models import *
from datetime import datetime, timedelta
from django.contrib import messages
from django.http import HttpResponseNotFound
from django.core.exceptions import ObjectDoesNotExist
import pytz

# Create your views here.
def create(request):
    if request.method == "POST":
        barang_nama = request.POST['barang_nama']
        barang_deskripsi = request.POST['barang_deskripsi']
        barang_url = request.POST['barang_url']
        lelang_startingbid = request.POST['lelang_startingbid']
        lelang_buyoutprice = request.POST['lelang_buyoutprice']
        lelang_minraise = request.POST['lelang_minraise']
        lelang_starttime = request.POST['lelang_starttime']
        lelang_endtime = request.POST['lelang_endtime']
        if (is_datetime_correct(lelang_starttime, lelang_endtime)):
            lelang_penjual = Penjual.objects.get(username=request.session['username'])
            barang = Barang.objects.create(barang_nama=barang_nama, barang_deskripsi=barang_deskripsi, barang_url=barang_url)
            lelang = Lelang.objects.create(lelang_penjual=lelang_penjual, lelang_barang=barang, lelang_startingbid=lelang_startingbid, lelang_buyout=lelang_buyoutprice,
                lelang_minraise=lelang_minraise, lelang_currentbid=lelang_startingbid, lelang_starttime=lelang_starttime, lelang_endtime=lelang_endtime)
            return redirect('/profil/lelang-dibuat')
        else :
            messages.info(request, "Input tanggal dan waktu yang diberikan tidak tepat!")
            return redirect(request.path_info)
    else:
        return render(request, 'lelang/create.html')

def is_datetime_correct(start, end):
    date_start = datetime.strptime(start, '%Y-%m-%dT%H:%M')
    date_end = datetime.strptime(end, '%Y-%m-%dT%H:%M')
    if (date_start < date_end and date_start > datetime.now()):
        return True
    return False

def update(request, id):
    try:
        if request.method == "POST":
            lelang = Lelang.objects.get(pk=id)
            lelang.lelang_barang.barang_nama = request.POST['barang_nama']
            lelang.lelang_barang.barang_deskripsi = request.POST['barang_deskripsi']
            lelang.lelang_barang.barang_url = request.POST['barang_url']
            lelang.lelang_startingbid = request.POST['lelang_startingbid']
            lelang.lelang_buyoutprice = request.POST['lelang_buyoutprice']
            lelang.lelang_minraise = request.POST['lelang_minraise']
            lelang.lelang_starttime = request.POST['lelang_starttime']
            lelang.lelang_endtime = request.POST['lelang_endtime']
            lelang.lelang_barang.save()
            lelang.save()
            return redirect('/profil/lelang-dibuat')
        else:
            lelang = Lelang.objects.get(pk=id)
            if (lelang.lelang_starttime - datetime.now(pytz.timezone('Asia/Bangkok')) <= timedelta(0)):
                messages.info(request, 'Lelang tidak dapat diedit dikarenakan lelang sudah dimulai')
            dct = {
                'dct_barang_nama' : lelang.lelang_barang.barang_nama,
                'dct_barang_deskripsi' : lelang.lelang_barang.barang_deskripsi,
                'dct_barang_url' : lelang.lelang_barang.barang_url,
                'dct_lelang_startingbid' : lelang.lelang_startingbid,
                'dct_lelang_buyoutprice' : lelang.lelang_buyout,
                'dct_lelang_minraise' : lelang.lelang_minraise,
                'dct_lelang_starttime' : lelang.lelang_starttime,
                'dct_lelang_endtime' : lelang.lelang_endtime,
            }
            return render(request, 'lelang/update.html', dct)
    except ObjectDoesNotExist:
        return HttpResponseNotFound("OBJECT DOES NOT EXIST")
            
       
def createtest(request):
    if request.method == "POST":
        pass
    else:
        return render(request, 'lelang/createtest.html')

def updatetest(request):
    if request.method == "POST":
        pass
    else:
        return render(request, 'lelang/updatetest.html')
        
def each_lelang(request, id):
    lelang = Lelang.objects.get(pk=id)
    username_penjual = lelang.get_penjual().username
    dct = {
        'lelang' : lelang,
        'owner_username' : username_penjual
    }
    if lelang.get_lelang_starttime() > datetime.now(pytz.timezone('Asia/Bangkok')):
        dct['editable'] = False
        if (lelang.get_status() == "Soon"):
            lelang.lelang_status = "Open"
            lelang.save()
    if lelang.get_lelang_endtime() < datetime.now(pytz.timezone('Asia/Bangkok')):
        dct['show_winner'] = True
    else:
        dct['editable'] = True
    return render(request, 'lelang/each_lelang.html', dct)

def raise_bid(request, id):
    authenticated = request.session.__contains__('username')
    if (authenticated):
        lelang = Lelang.objects.get(pk=id)

        is_penjual = request.session['username'] == lelang.get_username_penjual()
        if (is_penjual):
            return HttpResponseNotFound("404 NOT FOUND")
        else:

            # Kalau lelang belum dimulai
            if lelang.get_lelang_starttime() > datetime.now(pytz.timezone('Asia/Bangkok')):
                messages.info(request, "Belum dapat melakukan raise bid ataupun buyout untuk sementara waktu!")
                return redirect('lelang:each_lelang', id=id)

            # Kalau lelang telah berakhir
            if lelang.get_lelang_endtime() < datetime.now(pytz.timezone('Asia/Bangkok')):
                messages.info(request, "Pelelangan telah berakhir!")
                return redirect('lelang:each_lelang', id=id)
            
            # Kalau lelang sedang berjalan
            else:
                current_bid_price = lelang.get_currentbid_price()
                raise_bid_price = current_bid_price + lelang.get_minraise_price()
                user = Pengguna.objects.get(username=request.session['username'])
                current_saldo_user = user.get_saldo()
                old_highest_bidder = lelang.get_highestbidder()

                # Hanya bisa melakukan raise bid jika highest bidder sebelumnya bukan dirinya sendiri
                if user != old_highest_bidder:

                    # Check apakah saldo user cukup untuk raise bid
                    if (current_saldo_user >= raise_bid_price):
                        if lelang.get_highestbidder() is not None:
                            old_highest_bidder.set_saldo(old_highest_bidder.get_saldo() + current_bid_price)
                            old_highest_bidder.save()

                        user.set_saldo(user.get_saldo() - raise_bid_price)
                        user.save()

                        lelang.lelang_highestbidder = user
                        lelang.lelang_listpengguna.add(user)
                        lelang.lelang_currentbid = raise_bid_price

                        # Jika current bid terbaru melebihi atau sama dengan harga buyout
                        if lelang.get_currentbid_price() >= lelang.get_buyout_price():
                            lelang.lelang_endtime = datetime.now(pytz.timezone('Asia/Bangkok'))

                        lelang.save()
                        return redirect("lelang:each_lelang", id=id)
                    
                    # Jika saldo user yang melakukan raise bid tidak cukup
                    else:
                        messages.info(request, "Maaf, saldo anda tidak cukup!")
                        return redirect("lelang:each_lelang", id=id)
                
                # Jika raise bid yang highest bidder sebelumnya dirinya sendiri
                else:
                    messages.info(request, "Tidak dapat melakukan raise bid jika anda sebagai highest bidder")
                    return redirect("lelang:each_lelang", id=id)
    else:
        return HttpResponseNotFound("404 NOT FOUND")

def buyout(request, id):
    authenticated = request.session.__contains__('username')
    if (authenticated):
        lelang = Lelang.objects.get(pk=id)

        is_penjual = request.session['username'] == lelang.get_username_penjual()
        if (is_penjual):
            return HttpResponseNotFound("404 NOT FOUND")
        else:

            # Kalau lelang belum dimulai
            if lelang.get_lelang_starttime() > datetime.now(pytz.timezone('Asia/Bangkok')):
                messages.info(request, "Belum dapat melakukan raise bid ataupun buyout untuk sementara waktu!")
                return redirect('lelang:each_lelang', id=id)

            # Kalau lelang telah berakhir
            if lelang.get_lelang_endtime() < datetime.now(pytz.timezone('Asia/Bangkok')):
                messages.info(request, "Pelelangan telah berakhir!")
                return redirect('lelang:each_lelang', id=id)
            
            # Kalau lelang sedang berjalan
            else:
                current_bid_price = lelang.get_currentbid_price()
                buyout_price = lelang.get_buyout_price()
                user = Pengguna.objects.get(username=request.session['username'])
                current_saldo_user = user.get_saldo()
                old_highest_bidder = lelang.get_highestbidder()
                
                # Hanya bisa melakukan buyout jika highest bidder sebelumnya bukan dirinya sendiri
                if user != old_highest_bidder:
                    
                    # Check apakah saldo user cukup untuk buyout
                    if (current_saldo_user >= buyout_price):
                        if lelang.get_highestbidder() is not None:
                            old_highest_bidder.set_saldo(old_highest_bidder.get_saldo() + current_bid_price)
                            old_highest_bidder.save()

                        user.set_saldo(user.get_saldo() - buyout_price)
                        user.save()

                        lelang.lelang_highestbidder = user
                        lelang.lelang_listpengguna.add(user)

lelang/templates/lelang/create.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/lelang/lelang.css' %}">
{% endblock %}

{% block content %}

{% if "penjual" in request.session.role %}
<form class="form-create" method="POST" action="">
    {% csrf_token %}
    <div class="form-header">
        <p>Buat Lelang</p>  
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Nama Barang</p>
        </div>
        <div class="form-input">
            <input type="text" class="form" name="barang_nama" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Deskripsi Barang</p>
        </div>
        <div class="form-input">
            <input type="text" class="form" name="barang_deskripsi" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>URL Foto</p>
        </div>
        <div class="form-input">
            <input type="text" class="form" name="barang_url" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Starting Bid Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number" name="lelang_startingbid" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Buyout Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number" name="lelang_buyoutprice" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Minimum Raise Bid Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number" name="lelang_minraise" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Start Date</p>
        </div>
        <div class="form-input">
            <input type="datetime-local" class="form" name="lelang_starttime" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>End Date</p>
        </div>
        <div class="form-input">
            <input type="datetime-local" class="form" name="lelang_endtime" required>
        </div>
    </div>
    {% if messages %}
        <div style="color: red; margin-bottom: 0.5rem;">
            {% for message in messages %}
                <strong>{{ message }}</strong>
            {% endfor %}
        </div>
    {% endif %}
    <button class="lelang-button" type="submit">Buat Lelang</button>
</form>

{% elif 'penjual' not in request.session.role %}
    <div> 
        <center>
            <p>Silahkan register sebagai penjual untuk membuat lelang!</p>
        </center>
    </div>

{% elif request.session.username == None %}
    <div> 
        <center>
            <p>Silahkan login terlebih dahulu!</p>
        </center>
    </div>

{% endif %}

{% include 'footer.html' %}

{% endblock %}

lelang/templates/lelang/createtest.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/lelang/lelang.css' %}">
{% endblock %}

{% block content %}

<div class= form-create>
    <div class="form-header">
        <p>Buat Lelang</p>  
      </div>

      <div class="form-row">
          <div class="form-tag">
              <p>Nama Barang</p>
          </div>
          <div class="form-input">
              <input type="text" class="form">
          </div>
      </div>

      <div class="form-row">
        <div class="form-tag">
            <p>Deskripsi Barang</p>
        </div>
        <div class="form-input">
            <input type="text" class="form">
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>URL Foto</p>
        </div>
        <div class="form-input">
            <input type="text" class="form">
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Starting Bid Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number">
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Buyout Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number">
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Minimum Raise Bid Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number">
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Start Date</p>
        </div>
        <div class="form-input">
            <input type="datetime-local" class="form">
        </div>
    </div>

      <div class="form-row">
          <div class="form-tag">
              <p>End Date</p>
          </div>
          <div class="form-input">
              <input type="datetime-local" class="form">
          </div>
      </div>

      
      <button class="lelang-button" onclick="myFunction()">Buat Lelang</button>
</div>

{% include 'footer.html' %}

<script>
    function myFunction() {
      alert("Form tidak diisi dengan sempurna");
    }
</script>

{% endblock %}

lelang/templates/lelang/each_lelang.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/lelang/each_lelang.css' %}">
{% endblock %}

{% block content %}
<div class="perlelang">
    <p class="date">Closed at {{ lelang.get_lelang_endtime }}</p>
    <div class="perlelang-info">
        <div class="perlelang-image">
            <img src="{{ lelang.get_url_barang }}" alt="Barang Lelang" class="barang-lelang">
        </div>
        <div class="perlelang-detail">
            <p>{{ lelang.get_nama_barang }}</p>
            <p>{{ lelang.get_deskripsi_barang }}</p>
            <p>Buyout Price : Rp {{ lelang.get_buyout_price }},-</p>
            <p>Current Bid : Rp {{ lelang.get_currentbid_price }},-</p>
            <p>Minimum Raise Bid Price : Rp {{ lelang.get_minraise_price }},-</p>
            {% if messages %}
            <div style="color: red; margin-bottom: 0.5rem;">
                {% for message in messages %}
                    <strong>{{ message }}</strong>
                {% endfor %}
            </div>
            {% endif %}
            {% if editable %}
                {% if request.session.username != None and request.session.username != owner_username %}
                    <div class="perlelang-button">
                        <a href="{% url 'lelang:raisebid' id=lelang.pk %}"><button class="button raise-button">Raise Bid</button></a>
                        <a href="{% url 'lelang:buyout' id=lelang.pk %}"><button class="button buyout-button">Buyout</button></a>
                    </div>
                {% elif request.session.username == None %}
                    <p style="text-align: center;"> <a href="{% url 'authentication:login' %}"><button class="strict-button">Masuk untuk melanjutkan</button></a></p>
                {% endif %}
            {% elif show_winner %}
                {% if lelang.get_highestbidder == None %}
                <div style="color: red; margin-bottom: 0.5rem;">
                    Tidak ada pemenang dari pelelangan ini.
                </div>
                {% else %}
                    <div style="color: red; margin-bottom: 0.5rem;">
                        Pemenang dari lelang ini adalah user bernama: <strong>{{ lelang.get_highestbidder.nama }}</strong>
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>

{% include 'footer.html' %}
{% if lelang.get_status == "Open" %}
    <script src="{% static 'js/auto_refresh.js' %}"></script>
{% endif %}
{% endblock %}

lelang/templates/lelang/list_lelang.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/lelang/list_lelang.css' %}">
{% endblock %}

{% block content %}

{% if 'penjual' in request.session.role %}
    <a style="margin-left:auto" href="{% url 'lelang:create' %}">
        <button class="create-lelang-button">Create lelang</button>
    </a>
{% endif %}
<div class="container grid-lelang flex-wrap" style="min-height: 80vh;">
    {% for lelang in list_lelang %}
        <a href="{% url 'lelang:each_lelang' id=lelang.id %}" class="a-card-lelang">
            <div class="card-lelang flex-column">
                <img class="img-card-lelang" src="{{ lelang.lelang_barang.barang_url }}">
                <div class="desc-card-lelang">
                    <p class="mb-0 name-card-lelang">{{ lelang.lelang_barang.barang_nama }}</p>
                    <p class="mb-0 price-card-lelang">Rp {{ lelang.lelang_currentbid }}</p>
                </div>
            </div>
        </a>
    {% empty %}
        <p><b>Tidak ada barang yang dilelangkan</b></p>
    {% endfor %}
</div>

{% include 'footer.html' %}

{% endblock %}

lelang/templates/lelang/update.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/lelang/lelang.css' %}">
{% endblock %}

{% block content %}

{% if 'penjual' in request.session.role %}
    <form class= form-create method="POST" action="">
        {% csrf_token %}
        <div class="form-header">
            <p>Update Lelang</p>  
        </div>

        <div class="form-row">
            <div class="form-tag">
                <p>Nama Barang</p>
            </div>
            <div class="form-input">
                <input type="text" class="form" name="barang_nama" value="{{ dct_barang_nama }}" required>
            </div>
        </div>

        <div class="form-row">
        <div class="form-tag">
            <p>Deskripsi Barang</p>
        </div>
        <div class="form-input">
            <input type="text" class="form" name="barang_deskripsi" value="{{ dct_barang_deskripsi }}" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>URL Foto</p>
        </div>
        <div class="form-input">
            <input type="text" class="form" name="barang_url" value="{{ dct_barang_url }}" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Starting Bid Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number" name="lelang_startingbid" value="{{ dct_lelang_startingbid }}" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Buyout Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number" name="lelang_buyoutprice" value="{{ dct_lelang_buyoutprice }}" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Minimum Raise Bid Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number" name="lelang_minraise" value="{{ dct_lelang_minraise }}" required>
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Start Date</p>
        </div>
        <div class="form-input">
            <input type="datetime-local" class="form" name="lelang_starttime" value="{{ dct_lelang_starttime|date:'Y-m-d\TH:i' }}" required>
        </div>
    </div>

        <div class="form-row">
            <div class="form-tag">
                <p>End Date</p>
            </div>
            <div class="form-input">
                <input type="datetime-local" class="form" name="lelang_endtime" value="{{ dct_lelang_endtime|date:'Y-m-d\TH:i' }}" required>
            </div>
        </div>
        {% if messages %}
            <div style="color: red; margin-bottom: 0.5rem;">
                {% for message in messages %}
                    <strong>{{ message }}</strong>
                {% endfor %}
            </div>
        {% endif %}
        <button class="lelang-button" type="submit">Update Lelang</button>
        
    </form>
{% elif 'penjual' not in request.session.role %}
    <div> 
        <center>
            <p>Silahkan register sebagai penjual untuk mengedit lelang!</p>
        </center>
    </div>

{% elif request.session.username == None %}
    <div> 
        <center>
            <p>Silahkan login terlebih dahulu!</p>
        </center>
    </div>
    
{% endif %}

{% include 'footer.html' %}

{% endblock %}

lelang/templates/lelang/updatetest.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/lelang/lelang.css' %}">
{% endblock %}

{% block content %}

<div class= form-create>
    <div class="form-header">
        <p>Update Lelang</p>  
      </div>

      <div class="form-row">
          <div class="form-tag">
              <p>Nama Barang</p>
          </div>
          <div class="form-input">
              <input type="text" class="form">
          </div>
      </div>

      <div class="form-row">
        <div class="form-tag">
            <p>Deskripsi Barang</p>
        </div>
        <div class="form-input">
            <input type="text" class="form">
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>URL Foto</p>
        </div>
        <div class="form-input">
            <input type="text" class="form">
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Starting Bid Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number">
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Buyout Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number">
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Minimum Raise Bid Price</p>
        </div>
        <div class="form-input">
            Rp 
            <input type="number" class="form-number">
        </div>
    </div>

    <div class="form-row">
        <div class="form-tag">
            <p>Start Date</p>
        </div>
        <div class="form-input">
            <input type="datetime-local" class="form">
        </div>
    </div>

      <div class="form-row">
          <div class="form-tag">
              <p>End Date</p>
          </div>
          <div class="form-input">
              <input type="datetime-local" class="form">
          </div>
      </div>

      
      <button class="lelang-button"  onclick="myFunction()">Update Lelang</button>
</div>

{% include 'footer.html' %}


<script>
    function myFunction() {
      alert("Form tidak diisi dengan sempurna");
    }
</script>


{% endblock %}