arction/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('authentication.urls')),
    path('lelang/', include('lelang.urls')),
    path('profil/', include('profil.urls')),
]

authentication/urls.py
from django.urls import path
from .views import *

app_name = "authentication"

urlpatterns = [
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('logout/', logout, name="logout"),
    path('register-penjual/', daftar_sebagai_penjual, name="register-penjual"),
    path('register-penjual/respond', daftar_sebagai_penjual_respond, name="register-penjual-respond"),
    path('register-penjual/validation', admin_validation_page, name="admin-validation"),
    path('register-penjual/validation/accept/<int:id>', admin_validation_accept, name="admin-validation-accept"),
    path('register-penjual/validation/decline/<int:id>', admin_validation_decline, name="admin-validation-decline"),
]

homepage/urls.py
from django.urls import path
from .views import homepage

app_name = "homepage"

urlpatterns = [
    path('', homepage, name="homepage")
]

lelang/urls.py
from django.urls import path
from .views import *

app_name = "lelang"

urlpatterns = [
    path('create/', create, name="create"),
    path('update/<int:id>', update, name="update"),
    path('createtest/', createtest, name="createtest"),
    path('updatetest/', updatetest, name="updatetest"),
    path('<int:id>', each_lelang, name="each_lelang"),
    path('', list_lelang, name="list_lelang"),
    path('raisebid/<int:id>', raise_bid, name="raisebid"),
    path('buyout/<int:id>', buyout, name="buyout")
]

profil/urls.py
from django.urls import path
from .views import *

app_name = "profil"

urlpatterns = [
    path('history-terbeli/', history_terbeli, name="history_terbeli"),
    path('history-terjual/', history_terjual, name="history_terjual"),
    path('lelang-dibuat/', lelang_dibuat, name="lelang_dibuat"),
    path('lelang-diikuti/', lelang_diikuti, name="lelang_diikuti"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arction!</title>
    <link rel="stylesheet" href="{% static 'css/base/base.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script>
        $(document).ready(function(){
			$(".bell_wrap").click(function(){
			    $(".notif_dd").toggleClass("active");
			})
	    });
    </script>
    {% block stylesheet %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'homepage:homepage' %}">Arction</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="ml-auto-important navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'lelang:list_lelang' %}">Lelang</a>
                    </li>
                    {% if request.session.username %}
                        {% if 'pengguna' in request.session.role and 'penjual' not in request.session.role %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'authentication:register-penjual' %}">Daftar sebagai Penjual</a>
                            </li>
                        {% endif %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Profil
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'profil:history_terbeli' %}">Daftar Barang Terbeli</a></li>
                                {% if 'penjual' in request.session.role %}
                                    <li><a class="dropdown-item" href="{% url 'profil:history_terjual' %}">Daftar Barang Terjual</a></li>
                                {% endif %}
                                <li><a class="dropdown-item" href="{% url 'profil:lelang_diikuti' %}">Daftar Lelang yang Diikuti</a></li>
                                {% if 'penjual' in request.session.role %}
                                    <li><a class="dropdown-item" href="{% url 'profil:lelang_dibuat' %}">Daftar Lelang yang Dibuat</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authentication:logout' %}">Logout</a>
                        </li>
                        <div class="bell_wrap">
                            <img class="bell" src="{% static 'images/bell.png' %}">
                        </div>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authentication:login' %}">Masuk</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'authentication:register' %}">Daftar</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="notif_dd">
        <ul class="notif_ul">
            <li class="notif row">
                <div class="notif_icon col-2">
                    <img src="{% static 'images/gavel.png' %}">
                </div>
                <div class="col-7">
                    <div class="notif_title">Apel Kuning Merona</div>
                    <div class="notif_detail">Mohon maaf, barang sudah terjual.</div>
                </div>
                <div class="col-3">
                    <div class="notif_timer">just now</div>
                </div>
            </li>
            <li class="notif row">
                <div class="notif_icon col-2">
                    <img src="{% static 'images/gavel.png' %}">
                </div>
                <div class="col-7">
                    <div class="notif_title">Apel Kuning Merona</div>
                    <div class="notif_detail">Pelelalang sisa 1 jam lagi.</div>
                </div>
                <div class="col-3">
                    <div class="notif_timer">1 hour ago</div>
                </div>
            </li>
            <li class="notif row">
                <div class="notif_icon col-2">
                    <img src="{% static 'images/gavel.png' %}">
                </div>
                <div class="col-7">
                    <div class="notif_title">Apel Kuning Merona</div>
                    <div class="notif_detail">Pelelalang sisa 1 hari lagi.</div>
                </div>
                <div class="col-3">
                    <div class="notif_timer">23 hours ago</div>
                </div>
            </li>
            <li>
                <a class="showall" href="#">Show All Activities</a>
            </li>
        </ul>
    </div>
    {% block content %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<div class="footer">
    <p class="mb-0">Arction</p>
</div>